
import gui.PersonalizeGame;

/**
 *
 * @author USUARIO
 */
public class HomeGame extends javax.swing.JFrame {

    /**
     * Creates new form HomeGame
     */
    public HomeGame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        quickGame = new javax.swing.JButton();
        personalizeGame = new javax.swing.JButton();
        personalizeGame1 = new javax.swing.JButton();
        personalizeGame2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel2.setBackground(new java.awt.Color(51, 51, 51));
        jPanel2.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/thane.jpg"))); // NOI18N
        jLabel1.setText("jLabel1");

        quickGame.setBackground(new java.awt.Color(200, 150, 41));
        quickGame.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        quickGame.setForeground(new java.awt.Color(0, 0, 0));
        quickGame.setText("Partida Rápida");
        quickGame.setBorder(new javax.swing.border.MatteBorder(null));
        quickGame.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                quickGameActionPerformed(evt);
            }
        });

        personalizeGame.setBackground(new java.awt.Color(200, 150, 41));
        personalizeGame.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        personalizeGame.setForeground(new java.awt.Color(0, 0, 0));
        personalizeGame.setText("Partida Personalizada");
        personalizeGame.setBorder(new javax.swing.border.MatteBorder(null));
        personalizeGame.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                personalizeGameActionPerformed(evt);
            }
        });

        personalizeGame1.setBackground(new java.awt.Color(200, 150, 41));
        personalizeGame1.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        personalizeGame1.setForeground(new java.awt.Color(0, 0, 0));
        personalizeGame1.setText("Cargar última partida");
        personalizeGame1.setBorder(new javax.swing.border.MatteBorder(null));
        personalizeGame1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                personalizeGame1ActionPerformed(evt);
            }
        });

        personalizeGame2.setBackground(new java.awt.Color(200, 150, 41));
        personalizeGame2.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        personalizeGame2.setForeground(new java.awt.Color(0, 0, 0));
        personalizeGame2.setText("Ver lista de jugadores");
        personalizeGame2.setBorder(new javax.swing.border.MatteBorder(null));
        personalizeGame2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                personalizeGame2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(126, 126, 126)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(quickGame, javax.swing.GroupLayout.PREFERRED_SIZE, 263, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(personalizeGame, javax.swing.GroupLayout.PREFERRED_SIZE, 263, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(personalizeGame2, javax.swing.GroupLayout.PREFERRED_SIZE, 263, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(personalizeGame1, javax.swing.GroupLayout.PREFERRED_SIZE, 263, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 130, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 604, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(93, 93, 93)
                .addComponent(quickGame, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(69, 69, 69)
                .addComponent(personalizeGame, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(68, 68, 68)
                .addComponent(personalizeGame1, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(72, 72, 72)
                .addComponent(personalizeGame2, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void quickGameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_quickGameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_quickGameActionPerformed

    private void personalizeGameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_personalizeGameActionPerformed
        PersonalizeGame juegoPersonalizado = new PersonalizeGame();
        juegoPersonalizado.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_personalizeGameActionPerformed

    private void personalizeGame1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_personalizeGame1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_personalizeGame1ActionPerformed

    private void personalizeGame2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_personalizeGame2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_personalizeGame2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(HomeGame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(HomeGame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(HomeGame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(HomeGame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new HomeGame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JButton personalizeGame;
    private javax.swing.JButton personalizeGame1;
    private javax.swing.JButton personalizeGame2;
    private javax.swing.JButton quickGame;
    // End of variables declaration//GEN-END:variables
}
