package gui;

import java.util.Random;
import javax.swing.JOptionPane;
import logica.Army;
import logica.Jugar;
import logica.Player;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author USUARIO
 */
public class QuickGameWindows extends javax.swing.JFrame {

    /**
     * Creates new form QuickGameWindows
     */
    
    protected String reino1 = "";
    protected String terreno1 = "";
    
    protected String reino2 = "";
    protected String terreno2 = "";
    
    protected Army rojo;
    protected Army azul;

    protected String arenaFija;
    
    protected Random aleatorio = new Random();
    protected int opcion;
    
    protected Player playerRed;
    protected Player playerBlue;
    
  
    
    
    
    public QuickGameWindows(Player player1, Player player2) {
        playerRed = player1;
        playerBlue = player2;
        initComponents();
    }
    
    public QuickGameWindows() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        arenas1 = new javax.swing.JList<>();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        reinos1 = new javax.swing.JList<>();
        jLabel5 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        arenas2 = new javax.swing.JList<>();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        reinos2 = new javax.swing.JList<>();
        dirigirTablero = new javax.swing.JButton();
        generarEjercitos = new javax.swing.JButton();
        jugadorBlue = new javax.swing.JTextField();
        jugadorRed = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(0, 0, 0));

        jPanel2.setBackground(new java.awt.Color(255, 153, 153));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setText("Elija la arena");

        arenas1.setBackground(new java.awt.Color(255, 153, 153));
        arenas1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        arenas1.setForeground(new java.awt.Color(0, 0, 0));
        arenas1.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Montaña", "Bosque", "Playa", "Desierto", "Campo" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        arenas1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                arenas1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(arenas1);

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setText("Elija Reino");

        reinos1.setBackground(new java.awt.Color(255, 153, 153));
        reinos1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        reinos1.setForeground(new java.awt.Color(0, 0, 0));
        reinos1.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Sacro Imperio Romano", "Castilla-Aragón", "Inglaterra", "Moros", "Francia" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        reinos1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                reinos1MouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(reinos1);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 256, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 239, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(40, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 177, Short.MAX_VALUE)
                .addContainerGap())
        );

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/arthur.jpg"))); // NOI18N

        jPanel3.setBackground(new java.awt.Color(102, 102, 255));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 0));
        jLabel3.setText("Elija la arena");

        arenas2.setBackground(new java.awt.Color(102, 102, 255));
        arenas2.setBorder(null);
        arenas2.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        arenas2.setForeground(new java.awt.Color(0, 0, 0));
        arenas2.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Montaña", "Bosque", "Playa", "Desierto", "Campo" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        arenas2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                arenas2MouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(arenas2);

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 0, 0));
        jLabel4.setText("Elija Reino");

        reinos2.setBackground(new java.awt.Color(102, 102, 255));
        reinos2.setBorder(null);
        reinos2.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        reinos2.setForeground(new java.awt.Color(0, 0, 0));
        reinos2.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Sacro Imperio Romano", "Castilla-Aragón", "Inglaterra", "Moros", "Francia" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        reinos2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                reinos2MouseClicked(evt);
            }
        });
        jScrollPane4.setViewportView(reinos2);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel3Layout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 238, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                .addContainerGap(36, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 175, Short.MAX_VALUE)
                .addContainerGap())
        );

        dirigirTablero.setBackground(new java.awt.Color(153, 0, 0));
        dirigirTablero.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        dirigirTablero.setText("Jugar");
        dirigirTablero.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dirigirTableroActionPerformed(evt);
            }
        });

        generarEjercitos.setBackground(new java.awt.Color(0, 51, 0));
        generarEjercitos.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        generarEjercitos.setForeground(new java.awt.Color(255, 255, 255));
        generarEjercitos.setText("Generar Ejércitos");
        generarEjercitos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                generarEjercitosActionPerformed(evt);
            }
        });

        jugadorBlue.setEditable(false);
        jugadorBlue.setText("Esperando");

        jugadorRed.setEditable(false);
        jugadorRed.setText("Esperando");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(dirigirTablero, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(458, 458, 458))
            .addGroup(layout.createSequentialGroup()
                .addGap(53, 53, 53)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 304, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(16, 16, 16))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(generarEjercitos, javax.swing.GroupLayout.PREFERRED_SIZE, 215, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(58, 58, 58)))
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(54, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(103, 103, 103)
                .addComponent(jugadorRed, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jugadorBlue, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(143, 143, 143))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(43, 43, 43)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jugadorRed, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jugadorBlue, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 425, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(2, 2, 2)
                        .addComponent(generarEjercitos)))
                .addGap(29, 29, 29)
                .addComponent(dirigirTablero)
                .addContainerGap(38, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void dirigirTableroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dirigirTableroActionPerformed
        // TODO add your handling code here:
        
        if (generarEjercitos.isEnabled()){
            JOptionPane.showMessageDialog(rootPane, "Genere los ejércitos!");
            return;
        }
        this.dispose();
        Tablero tab = new Tablero(rojo, azul, arenaFija);
        
        Jugar jugar = new Jugar( tab, rojo, azul, arenaFija, playerRed, playerBlue);
        
        jugar.game();
        
        
    }//GEN-LAST:event_dirigirTableroActionPerformed

    private void generarEjercitosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_generarEjercitosActionPerformed
        // TODO add your handling code here:
        if (terreno1.equals("") || terreno1.equals("")) {
            JOptionPane.showMessageDialog(rootPane, "Seleccione la arena de juego!");
            return;
        }
        
        if (reino1.equals("") || reino2.equals("")) {
            JOptionPane.showMessageDialog(rootPane, "Seleccione un reino!");
            return;
        }
        

        
        if (playerRed == null || playerBlue == null) {
            jugadorRed.setText(reino1);
            jugadorBlue.setText(reino2);
        } else {
            jugadorRed.setText(playerRed.getNombre());
            jugadorBlue.setText(playerBlue.getNombre());
        }
        
        rojo = new Army(reino1);
        azul = new Army(reino2);
        rojo.generateArmy(azul);
        azul.generateArmy(rojo);
        
        opcion = aleatorio.nextInt(2);
        if (opcion == 0){
            arenaFija = terreno1;
        } else {
            arenaFija = terreno2;
        }
        azul.showArmy();
        rojo.showArmy();
        generarEjercitos.setEnabled(false);
        System.out.println(azul.getName( ));
        System.out.println(rojo.getName( ));
       
    }//GEN-LAST:event_generarEjercitosActionPerformed
    
    
    private void reinos1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_reinos1MouseClicked
        // TODO add your handling code here:
        reino1 = reinos1.getSelectedValue();
    }//GEN-LAST:event_reinos1MouseClicked

    private void arenas1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_arenas1MouseClicked
        // TODO add your handling code here:
        terreno1 = arenas1.getSelectedValue();
        System.out.println(terreno1);
    }//GEN-LAST:event_arenas1MouseClicked

    private void reinos2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_reinos2MouseClicked
        // TODO add your handling code here:
        reino2 = reinos2.getSelectedValue();
    }//GEN-LAST:event_reinos2MouseClicked

    private void arenas2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_arenas2MouseClicked
        // TODO add your handling code here:
        terreno2 = arenas2.getSelectedValue();
    }//GEN-LAST:event_arenas2MouseClicked
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(QuickGameWindows.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(QuickGameWindows.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(QuickGameWindows.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(QuickGameWindows.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new QuickGameWindows().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JList<String> arenas1;
    private javax.swing.JList<String> arenas2;
    private javax.swing.JButton dirigirTablero;
    private javax.swing.JButton generarEjercitos;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTextField jugadorBlue;
    private javax.swing.JTextField jugadorRed;
    private javax.swing.JList<String> reinos1;
    private javax.swing.JList<String> reinos2;
    // End of variables declaration//GEN-END:variables
}
