package gui;

import logica.Aplicacion;

/**
 *
 * @author USUARIO
 */
public class HomeGame extends javax.swing.JFrame {

    /**
     * Creates new form HomeGame
     */
    
    public HomeGame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        partidaRapida = new javax.swing.JButton();
        personalizeGame = new javax.swing.JButton();
        registar = new javax.swing.JButton();
        personalizeGame2 = new javax.swing.JButton();
        personalizeGame3 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel2.setBackground(new java.awt.Color(51, 51, 51));
        jPanel2.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        partidaRapida.setBackground(new java.awt.Color(200, 150, 41));
        partidaRapida.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        partidaRapida.setForeground(new java.awt.Color(0, 0, 0));
        partidaRapida.setText("Partida Rápida");
        partidaRapida.setBorder(new javax.swing.border.MatteBorder(null));
        partidaRapida.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                partidaRapidaActionPerformed(evt);
            }
        });

        personalizeGame.setBackground(new java.awt.Color(200, 150, 41));
        personalizeGame.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        personalizeGame.setForeground(new java.awt.Color(0, 0, 0));
        personalizeGame.setText("Partida Personalizada");
        personalizeGame.setBorder(new javax.swing.border.MatteBorder(null));
        personalizeGame.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                personalizeGameActionPerformed(evt);
            }
        });

        registar.setBackground(new java.awt.Color(200, 150, 41));
        registar.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        registar.setForeground(new java.awt.Color(0, 0, 0));
        registar.setText("Registrar Retadores");
        registar.setBorder(new javax.swing.border.MatteBorder(null));
        registar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                registarActionPerformed(evt);
            }
        });

        personalizeGame2.setBackground(new java.awt.Color(200, 150, 41));
        personalizeGame2.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        personalizeGame2.setForeground(new java.awt.Color(0, 0, 0));
        personalizeGame2.setText("Ver lista de jugadores");
        personalizeGame2.setBorder(new javax.swing.border.MatteBorder(null));
        personalizeGame2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                personalizeGame2ActionPerformed(evt);
            }
        });

        personalizeGame3.setBackground(new java.awt.Color(200, 150, 41));
        personalizeGame3.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        personalizeGame3.setForeground(new java.awt.Color(0, 0, 0));
        personalizeGame3.setText("Cargar última partida");
        personalizeGame3.setBorder(new javax.swing.border.MatteBorder(null));
        personalizeGame3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                personalizeGame3ActionPerformed(evt);
            }
        });

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/thane.jpg"))); // NOI18N

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(126, 126, 126)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(partidaRapida, javax.swing.GroupLayout.PREFERRED_SIZE, 263, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(personalizeGame, javax.swing.GroupLayout.PREFERRED_SIZE, 263, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(personalizeGame2, javax.swing.GroupLayout.PREFERRED_SIZE, 263, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(registar, javax.swing.GroupLayout.PREFERRED_SIZE, 263, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(personalizeGame3, javax.swing.GroupLayout.PREFERRED_SIZE, 263, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 111, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 563, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(93, 93, 93)
                .addComponent(partidaRapida, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(46, 46, 46)
                .addComponent(personalizeGame, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(39, 39, 39)
                .addComponent(personalizeGame3, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(43, 43, 43)
                .addComponent(registar, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33)
                .addComponent(personalizeGame2, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(43, Short.MAX_VALUE))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 531, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void partidaRapidaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_partidaRapidaActionPerformed
        // TODO add your handling code here:
        QuickGameWindows quick = new QuickGameWindows(null, null);
        quick.setVisible(true);
        this.dispose();
        
    }//GEN-LAST:event_partidaRapidaActionPerformed

    private void personalizeGameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_personalizeGameActionPerformed
        PersonalizeGame juegoPersonalizado = new PersonalizeGame();
        juegoPersonalizado.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_personalizeGameActionPerformed

    private void registarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_registarActionPerformed
        // TODO add your handling code here:
        Login login = new Login();
        login.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_registarActionPerformed

    private void personalizeGame2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_personalizeGame2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_personalizeGame2ActionPerformed

    private void personalizeGame3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_personalizeGame3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_personalizeGame3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(HomeGame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(HomeGame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(HomeGame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(HomeGame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new HomeGame().setVisible(true);
            }
        });
        
        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JButton partidaRapida;
    private javax.swing.JButton personalizeGame;
    private javax.swing.JButton personalizeGame2;
    private javax.swing.JButton personalizeGame3;
    private javax.swing.JButton registar;
    // End of variables declaration//GEN-END:variables
    
}
